# Generated by Django 3.2 on 2024-05-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
