# Generated by Django 4.2.5 on 2024-06-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='contracttype',
            field=models.CharField(choices=[('دوام كامل', 'دوام كامل'), ('دوام جزئي', 'دوام جزئي'), ('عمل عن بعد', 'عمل عن بعد')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='jobtype',
            field=models.CharField(choices=[('جهة خاصة', 'جهة خاصة'), ('جهة حكومية', 'جهة حكومية')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.CharField(choices=[('أبوظبي', 'أبوظبي'), ('دبي', 'دبي'), ('الشارقة', 'الشارقة'), ('الفحيرة', 'الفحيرة'), ('راس الخيمة', 'راس الخيمة'), ('عجمان', 'عجمان')], max_length=10),
        ),
    ]
